---
- name: Import Red Hat / CentOS tasks
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- block:
  - name: Enable service snapd and ensure it is started
    systemd:
      name: snapd
      enabled: yes
      state: started

  - name: Enable classic snap support
    file:
      src: /var/lib/snapd/snap
      dest: /snap
      state: link
  become: yes