---
- hosts: localhost
  tasks:
  - import_role:
      name: common-dev-packages
    tags: ["common-dev-packages"]

  - import_role:
      name: snap
    tags: ["snap"]

  - import_role:
      name: flatpak
    tags: ["flatpak"]

  - import_role:
      name: git
    tags: ["git"]

  - import_role:
      name: openjdk
    tags: ["openjdk"]

  - import_role:
      name: pyenv
    tags: ["pyenv"]

  - import_role:
      name: neovim
    tags: ["neovim"]

  - import_role:
      name: tmux
    tags: ["tmux"]

  - import_role:
      name: dbeaver
    tags: ["dbeaver"]