---
- name: Import Red Hat / CentOS tasks
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Set java environment variables in /etc/profile.d/openjdk.sh
  blockinfile:
    insertafter: EOF
    path: /etc/profile.d/openjdk.sh
    block: |
      export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which javac)))))
      export PATH=$PATH:$JAVA_HOME/bin
      export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
    create: yes
  become: yes